apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - external-secrets.yaml
  - onepassword-connect.yaml
  - onepassword-cluster-secret-store.yaml
  - self-signed-issuer.yaml
